sudo: required
language: node_js
node_js:
- stable
services:
- docker
before_install:
- npm install
- echo "Testing Docker Hub credentials"
- BUILDID="build-$RANDOM"
- docker login -u=$GITUSENAME -p=$GITPASSWRD
- echo "Docker Hub credentials are working"
script:
- docker ps -a
after_success:
- docker build . -t $GITUSENAME/ledgeriumkyc:v$BUILDID
- docker push $GITUSENAME/ledgeriumkyc:v$BUILDID
env:
  global:
  - secure: W7ZujeEMBWauP7dU+wNzIn/wv7/Axt15McA3LCMVF5XgK4wYjEvwLvTkLz5rldrBiC+wBizLfYP0Ejefkmbg6nLi23wMc5SimXsc0TB1R/EgC5aEVYDMm8wEEJQpVAHy/mzJltRK7ZuSG2TG1eAo3mfomfQy4QmPPH3N/jnEhQMWddC0P7D1bNk1dhHbc1vDCBlUFfGnfH4v7+3xoMIoxX8nA9vyKAKdhuQYSlmfjftlKqXrirILyyERzB2xHvaUT5mIF1RKLFQ6TUrFLRUnxzDKPjREbfUaH3X9mhEHSpZCLI+uorx94ybSuo+VNvrYoNGKN14UQ9UTxuNJVUmE9QCrI+/iZ1iDRGtrhFYZY1SM2Cm0V2Fg893HlVO8EvhM9Ow2d/wNeewWd3mhEM0r4lEeVc6eCRm1J0DuwA9zXtU+EtDN8XFxBvPHJ8WIfFyCSc6pSfUznLNEe190cKLs/USLBtYGfqqeVFtD0603VQL74Z8ZOV16R03an+7jITnZYcLrHwQU4w9J4Ryj/xNg2r5i6iInalJH20buBtaeQtZdBT0q3xPLEMoar0T51zZMcm6h55lm+CCk6cXaKMKLgZh/4RiVa9piAstS4TkR1X85ZOHYW+B9v8CrC8n9/T5MQXs8p4ikODnDos2EG4XE3tMoqE+xH5ZwxieQD9M+mJ0=
  - secure: r9PuhY28pP7/0RWR9lub8jkFDWn32u55kDoT4QmPFrBNRG0ru+uDjJOQtMEY+5I6xX2JQybOu+N1m6EJ5ckNnUTcf70d8eoxpg/82lEHOaSXvqZIUrxSyknSe8ALnrIz4aYIuqtedxv0rA4W/N2tn2cYRKUPI6mCQu0OhHhKJ/fTV4qlJ//b+uiiYMl38nfY7ISPyHJU/6JeaS6LCWcArAGKTxtNKkpIZteNsQg8Apen6sSB8iVyfF6Jm4oSZWTYlUxRhk/1D670GDJjNqHEI7g34zOIL22wKcSPOl0Ermma/4ZaTlf2j8ck2DcejXnufwErG+d3nRtL+2IeWD7sWAJCSga8h1zHkVKSh6TdtG2c2hMybaO1QRoYjbmOAd3wLGMw7iUtXBOpwKvuf3gggXII9ZV+8KLHjfFxkRC5wEFe1XLc2H8yeExnBWKHJxcsw7eLFOwWKf0m6HbfcMVx2MFkhIbjy/bPD8ZHIew58bej5/wi1MNByIGFoA/B5FjBBJEyJFQN08xtuW3mx6/N8VTdRg+dr/w3utM1rmSKxhuNnHU5EuOcBpv+whTZIYyrc47NCgTNx3U/2aeJRPp1oXSqifSL5DZAk/wqigx+oCbrgiNAoP01mlS/mspUfCHqim85iz6v0N1yg2KohMwITVoHxq2xVU0VbAW2p37fwag=
