sudo: required
language: node_js
node_js:
- node
env:
  - SERVER_IP_ADDRESS=104.210.106.138
services:
- docker
addons:
  ssh_known_hosts: 104.210.106.138
before_install:
- npm install
- echo "Testing Docker Hub credentials"
- BUILDID="build-$RANDOM"
- echo $BUILDID
- docker login -u=$DOCUSENAME -p=$DOCPASSWRD
- echo "Docker Hub credentials are working"
script:
- docker ps -a
after_success:
- docker build . -t $DOCUSENAME/ledgeriumkyc:v$BUILDID
- docker push $DOCUSENAME/ledgeriumkyc:v$BUILDID
before_deploy:
- openssl aes-256-cbc -K $encrypted_912f6b4f611e_key -iv $encrypted_912f6b4f611e_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- rsync -r --delete-after --quiet ./deploy_script.sh ledgerappuser@104.210.106.138:~/ledgerium/ledgeriumkyc
# test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
#- ssh -i ./deploy_key ledgerappuser@104.210.106.138 "pwd && cd ~/ledgerium/ledgeriumkyc && docker-compose down && docker pull $DOCUSENAME/ledgeriumkyc:vbuild-29996 && docker-compose up -d"
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy_script.sh $BUILDID
  on:
    branch: master
env:
  global:
  - secure: 0QFvA76+JrDJ6DLIAVCTTiBFgbR37jbE22/HFE7w9axo8OZIqm4BQqysL08ZttuJjqot4yFtQD3CKRKH6vegiYHH78lWVHUiyvQKyR1CistIqGiyOHrdDFAr9tnD5NHl2Veu0PGKNPE6+D1TIFYF6rod6VVHZSJvXshAC/YBJ1yN4lavwHnaiXk5vcSl6LgOd4nQ4IqTxMhcpdi0nc2KMPu1DM6pT3L936bwrC0lVwsukgpnhuls8NRVPLVQNOXZlT/ka3xzE94Vt1tLQZMEVqbx4y5TXiBygPINNuUXKyqNX5Z1IImaZmO9e54hWqSu4nrPCNDTimO5rWCtEtInSjWZPyXoBg0dvuXy5oPiS26b7ZjN8dTFeyVCnq0piSgqEaIO/sI5uZ2LWfeRDNOWdy3p+2rQ1gMT1gotVgbOSUnQp1WZfKZpPhql4VJk00vALrss8OjOpGVb/d3YpWhhVWMrB47MCORv5ygZ6WRiVV2TNV/pABN1UpFQT5V/F0w2xXocXOuA4bcmlAqQHFGVFvxF5zbZn/K9EAkqiFwgT+JBjyNiz6Kjg4bGoBqNvdKnL+KIXnEEi8IIQNslN8fWovuxbr4JExkwrx5GoOGtTb3ASqWHNGn4PZNyDTaJElMVTsSoJxMA1vEIu5vClEfOciMAHWMaf3OOrLIYJfDWJeM=
  - secure: DWGsnTABpIxM8dJRwjzwYN05qCGFJFahCVrH9DiHTWz7mnjJZjR5SYwfc3kG/AXqGWEKKs0Ceki28fy0vZ1Nnbr0Ap6ZhkuUAeuJSX9CGNZCTs+v38i8CaCFdu2ihFxalwVgtlQ+Ppt/kApmILLiLKSLa+AiGqaNyeRIXlLdw5avxLhvathDiEePknppXNcXlsX95X0AUS30T/No0b1L+tvR3spcFeJXTarC7B4IWS0NivQBdnCY3alFSDC4z4tv1ZYy0GZD8R5E4PhpxrQicPEfNBekNW1tTM3b1TZeoa1zZG37LHQP8z2PJVTiyuGyvvG8mmvwYetM/ZXx7DEc+wtjMg3t/hFaU5XcAKE1q1JLr/dSw97XbBSykxEPQAO+1gliqDOQzXED+Z5fd/Y8sjGCz/AuA4NGo5zMpHaHZ5R8+zIRl2/NuPJ3yey1giuMrZuaB+1BPFOB51UgX6R01kv4fVWHXW2CKpVPIcyTgQxVpIh2NKJ6yROVGKGdElOThcVw+W9bNd468k++PNeRuSFe6vZBXKBKjAncbmtVoYU0CXWvFIgExJRhK/1BqIAW1d+ezXXppC9c7ZiPV3uk+BY+kFaBcZNrehduqVXzADHIYYaKHoBORhL1OOurxJynXLAcbwrM38XVwjjHxClqMj0GbNBrRUEaTgIaY5mNCiQ=