sudo: required
language: node_js
node_js:
- stable
services:
- docker
before_install:
- npm install
- echo "Testing Docker Hub credentials"
- BUILDID="build-$RANDOM"
- echo $BUILDID
- docker login -u=$DOCUSENAME -p=$DOCPASSWRD
- echo "Docker Hub credentials are working"
script:
- docker ps -a
after_success:
- docker build . -t $DOCUSENAME/ledgeriumkyc:v$BUILDID
- docker push $DOCUSENAME/ledgeriumkyc:v$BUILDID
before_deploy:
- echo "Pushing image"
deploy:
  - provider: script
    script: echo 'Hello'
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: echo 'World'
    on:
      branch: master
env:
  global:
  - secure: 0QFvA76+JrDJ6DLIAVCTTiBFgbR37jbE22/HFE7w9axo8OZIqm4BQqysL08ZttuJjqot4yFtQD3CKRKH6vegiYHH78lWVHUiyvQKyR1CistIqGiyOHrdDFAr9tnD5NHl2Veu0PGKNPE6+D1TIFYF6rod6VVHZSJvXshAC/YBJ1yN4lavwHnaiXk5vcSl6LgOd4nQ4IqTxMhcpdi0nc2KMPu1DM6pT3L936bwrC0lVwsukgpnhuls8NRVPLVQNOXZlT/ka3xzE94Vt1tLQZMEVqbx4y5TXiBygPINNuUXKyqNX5Z1IImaZmO9e54hWqSu4nrPCNDTimO5rWCtEtInSjWZPyXoBg0dvuXy5oPiS26b7ZjN8dTFeyVCnq0piSgqEaIO/sI5uZ2LWfeRDNOWdy3p+2rQ1gMT1gotVgbOSUnQp1WZfKZpPhql4VJk00vALrss8OjOpGVb/d3YpWhhVWMrB47MCORv5ygZ6WRiVV2TNV/pABN1UpFQT5V/F0w2xXocXOuA4bcmlAqQHFGVFvxF5zbZn/K9EAkqiFwgT+JBjyNiz6Kjg4bGoBqNvdKnL+KIXnEEi8IIQNslN8fWovuxbr4JExkwrx5GoOGtTb3ASqWHNGn4PZNyDTaJElMVTsSoJxMA1vEIu5vClEfOciMAHWMaf3OOrLIYJfDWJeM=
  - secure: DWGsnTABpIxM8dJRwjzwYN05qCGFJFahCVrH9DiHTWz7mnjJZjR5SYwfc3kG/AXqGWEKKs0Ceki28fy0vZ1Nnbr0Ap6ZhkuUAeuJSX9CGNZCTs+v38i8CaCFdu2ihFxalwVgtlQ+Ppt/kApmILLiLKSLa+AiGqaNyeRIXlLdw5avxLhvathDiEePknppXNcXlsX95X0AUS30T/No0b1L+tvR3spcFeJXTarC7B4IWS0NivQBdnCY3alFSDC4z4tv1ZYy0GZD8R5E4PhpxrQicPEfNBekNW1tTM3b1TZeoa1zZG37LHQP8z2PJVTiyuGyvvG8mmvwYetM/ZXx7DEc+wtjMg3t/hFaU5XcAKE1q1JLr/dSw97XbBSykxEPQAO+1gliqDOQzXED+Z5fd/Y8sjGCz/AuA4NGo5zMpHaHZ5R8+zIRl2/NuPJ3yey1giuMrZuaB+1BPFOB51UgX6R01kv4fVWHXW2CKpVPIcyTgQxVpIh2NKJ6yROVGKGdElOThcVw+W9bNd468k++PNeRuSFe6vZBXKBKjAncbmtVoYU0CXWvFIgExJRhK/1BqIAW1d+ezXXppC9c7ZiPV3uk+BY+kFaBcZNrehduqVXzADHIYYaKHoBORhL1OOurxJynXLAcbwrM38XVwjjHxClqMj0GbNBrRUEaTgIaY5mNCiQ=
