# simplifed version of the upstream travis configuration
sudo: required
language: node_js
node_js:
  - stable
services:
  - docker

before_install:
  - npm install
  - echo "Testing Docker Hub credentials"
  - BUILDID="build-$RANDOM"
  - docker login -u=golra03 -p=abcd_1234
  - echo "Docker Hub credentials are working"
 
script:
  - docker ps -a

after_success:
  - docker build . -t golra03/ledgeriumkyc:v$BUILDID
  - docker push golra03/ledgeriumkyc:v$BUILDID