# simplifed version of the upstream travis configuration
sudo: required
language: node_js
node_js:
  - stable
services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - BUILDID="build-$RANDOM"
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Docker Hub credentials are working"
 
script:
  - docker ps -a

after_success:
  - docker build . -t $DOCKER_USERNAME/ledgeriumkyc:v$BUILDID
  - docker push $DOCKER_USERNAME/ledgeriumkyc:v$BUILDID

