version: '3'
services:
  mongodbkyc:
    image: 'mongo:3.4.10'
    container_name: mongodbkyc
    ports:
      - '27018:27018'
    entrypoint: mongod --smallfiles --logpath=/dev/null --bind_ip '0.0.0.0'
    networks:
      test_net:
        ipv4_address: 172.19.240.78
  ledgeriumkyc:
    image: 'ledgeriumengineering/ledgeriumkyc:v1.0'
    environment:
      - SERVER_PORT=5002
      - MONGO_HOST=172.19.240.78
      - MONGO_DB=kyc
    volumes:
      - './logs:/logs'
    ports:
      - '5002:5002'
    depends_on:
      - mongodbkyc
    restart: always
    entrypoint:
      - /bin/sh
      - '-c'
      - >
        set -u

        set -e

        mkdir -p /logs/ledgeriumkyclogs

        DATE=`date '+%Y-%m-%d_%H-%M-%S'`

        node index.js
    networks:
      test_net:
        ipv4_address: 172.19.240.77
volumes: {}
networks:
  test_net:
    external: true